### ISSUE TITLE
sqlalchemy exception on Debian 12

### ISSUE THREAD

**Issue by senier** [treiher/valens#29]
I installed valens using pip as described in the README:

```console
$ python3.11 -m venv .venv
$ . .venv/bin/activate
$ pip install valens
[...]
Successfully installed Jinja2-3.1.2 Mako-1.3.0 MarkupSafe-2.1.3 Werkzeug-3.0.1 alembic-1.8.0 blinker-1.7.0 click-8.1.7 contourpy-1.2.0 cycler-0.12.1 flask-3.0.0 fonttools-4.4
7.0 greenlet-3.0.3 itsdangerous-2.1.2 kiwisolver-1.4.5 matplotlib-3.8.2 mypy-1.8.0 mypy-extensions-1.0.0 numpy-1.26.2 packaging-23.2 pandas-2.1.4 pillow-10.1.0 pyparsing-3.1.
1 python-dateutil-2.8.2 pytz-2023.3.post1 six-1.16.0 sqlalchemy-2.0.23 sqlalchemy-repr-0.1.0 typing-extensions-4.9.0 tzdata-2023.3 valens-0.2.0
$
```

Doing anything with `valens` (e.g. `valens demo`) yields an exception:

```console
Traceback (most recent call last):
  File "/home/senier/tmp/.venv/bin/valens", line 5, in <module>
    from valens.cli import main
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/valens/__init__.py", line 3, in <module>
    from . import api, assets
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/valens/api.py", line 14, in <module>
    from valens import database as db, version
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/valens/database.py", line 12, in <module>
    from valens import config, models
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/valens/models.py", line 49, in <module>
    class User(Base):
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 563, in __init__
    self._scan_attributes()
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1006, in _scan_attributes
    collected_annotation = self._collect_annotation(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1277, in _collect_annotation
    extracted = _extract_mapped_subtype(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/senier/tmp/.venv/lib/python3.11/site-packages/sqlalchemy/orm/util.py", line 2382, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "User.body_weight" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
```

This issue does not occur with the current main (`valens-0.2.1.dev92+71f3cd1` installed using `pip install git+https://github.com/treiher/valens`)

**Comment by treiher** [comment]
Thanks for the report! I guess this is caused by incompatibilities introduced by SQLAlchemy 2.0. You could try installing `sqlalchemy <2` to fix this issue. The problem is already fixed on `main`. I will release a new version soon that also contains several other improvements.

**Comment by senier** [comment]
You're right - restricting the sqlalchemy version works around the problem:

```console
$ pip install valens 'sqlalchemy<2.0'
```

Closing this ticket. Looking forward to the new release :smiley:
