### ISSUE TITLE
Occasional panic

### ISSUE THREAD

**Issue by treiher** [treiher/valens#73]
```
panicked at /rust/deps/dlmalloc-0.2.6/src/dlmalloc.rs:1198:13:
assertion failed: psize <= size + max_overhead

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157.js:432:21)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::Error::new::ha4e9991f32247831 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[24532]:0xb43395)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::hook_impl::h85421c2be90e5a21 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[7452]:0x8a7965)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::hook::h4f1be93b922a29bb (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[27693]:0xb6d479)
    at valens_frontend-43c877bf570dda15.wasm.core::ops::function::Fn::call::hab190eeeb64b5b6b (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[23535]:0xb33946)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[11797]:0x9d7569)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[15079]:0xa68297)
    at valens_frontend-43c877bf570dda15.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[29763]:0xb7e030)
    at valens_frontend-43c877bf570dda15.wasm.rust_begin_unwind (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[21544]:0xb104a0)
    at valens_frontend-43c877bf570dda15.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[22202]:0xb1cbf9)
```

```
Uncaught RuntimeError: unreachable
    at valens_frontend-43c877bf570dda15.wasm.__rust_start_panic (valens-frontend-ba38…57_bg.wasm:0xb7e107)
    at valens_frontend-43c877bf570dda15.wasm.rust_panic (valens-frontend-ba38…57_bg.wasm:0xb7cb07)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (valens-frontend-ba38…57_bg.wasm:0x9d7594)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (valens-frontend-ba38…57_bg.wasm:0xa68297)
    at valens_frontend-43c877bf570dda15.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (valens-frontend-ba38…57_bg.wasm:0xb7e030)
    at valens_frontend-43c877bf570dda15.wasm.rust_begin_unwind (valens-frontend-ba38…57_bg.wasm:0xb104a0)
    at valens_frontend-43c877bf570dda15.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (valens-frontend-ba38…57_bg.wasm:0xb1cbf9)
    at valens_frontend-43c877bf570dda15.wasm.core::panicking::panic::hcaca2598a27ec0fc (valens-frontend-ba38…57_bg.wasm:0xb40efb)
    at valens_frontend-43c877bf570dda15.wasm.__rdl_dealloc (valens-frontend-ba38…57_bg.wasm:0xadb172)
    at valens_frontend-43c877bf570dda15.wasm.__rust_dealloc (valens-frontend-ba38…57_bg.wasm:0xb7cacd)
```

```
panicked at /home/devel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/seed-0.8.0/src/app.rs:341:14:
missing root element

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8000/valens-frontend-ba383f5….js:432:21)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::Error::new::ha4e9991f32247831 (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[24532]:0xb43395)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::hook_impl::h85421c2be90e5a21 (http://localhost:8000/valens-frontend-ba383f5……123c576…_bg.wasm:wasm-function[7452]:0x8a7965)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::hook::h4f1be93b922a29bb (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[27693]:0xb6d479)
    at valens_frontend-43c877bf570dda15.wasm.core::ops::function::Fn::call::hab190eeeb64b5b6b (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[23535]:0xb33946)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[11797]:0x9d7569)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[15079]:0xa68269)
    at valens_frontend-43c877bf570dda15.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[29763]:0xb7e030)
    at valens_frontend-43c877bf570dda15.wasm.rust_begin_unwind (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[21544]:0xb104a0)
    at valens_frontend-43c877bf570dda15.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://localhost:8000/valens-frontend-ba383f5……23c5763…_bg.wasm:wasm-function[22202]:0xb1cbf9)
```

```
Uncaught RuntimeError: unreachable
    at valens_frontend-43c877bf570dda15.wasm.__rust_start_panic (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xb7e107)
    at valens_frontend-43c877bf570dda15.wasm.rust_panic (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xb7cb07)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0x9d7594)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xa68269)
    at valens_frontend-43c877bf570dda15.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xb7e030)
    at valens_frontend-43c877bf570dda15.wasm.rust_begin_unwind (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xb104a0)
    at valens_frontend-43c877bf570dda15.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xb1cbf9)
    at valens_frontend-43c877bf570dda15.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xae36c4)
    at valens_frontend-43c877bf570dda15.wasm.core::option::Option<T>::expect::h6e90af5535e1cc31 (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0xa69d57)
    at valens_frontend-43c877bf570dda15.wasm.seed::app::App<Ms,Mdl,INodes>::rerender_vdom::hc2555c1cbe71cc9b (valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:0x29d3ec)
```

```
panicked at /home/devel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/seed-0.8.0/src/app.rs:339:14:
already borrowed: BorrowMutError

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157.js:432:21)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::Error::new::ha4e9991f32247831 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[24532]:0xb43395)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::hook_impl::h85421c2be90e5a21 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[7452]:0x8a7965)
    at valens_frontend-43c877bf570dda15.wasm.console_error_panic_hook::hook::h4f1be93b922a29bb (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[27693]:0xb6d479)
    at valens_frontend-43c877bf570dda15.wasm.core::ops::function::Fn::call::hab190eeeb64b5b6b (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[23535]:0xb33946)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[11797]:0x9d7569)
    at valens_frontend-43c877bf570dda15.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[15079]:0xa68269)
    at valens_frontend-43c877bf570dda15.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[29763]:0xb7e030)
    at valens_frontend-43c877bf570dda15.wasm.rust_begin_unwind (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[21544]:0xb104a0)
    at valens_frontend-43c877bf570dda15.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://localhost:8000/valens-frontend-ba383f56ca85444a5555da7d7d3d98d5c1f578cc8d6c652ae2c68d27d51123c57638c7f0789bba7c5befb75a4c0db157_bg.wasm:wasm-function[22202]:0xb1cbf9)
```

**Comment by treiher** [comment]
This is probably caused by https://github.com/rustwasm/wasm-bindgen/issues/3801. We either need to update wasm-bindgen to 0.2.91 or downgrade the Rust toolchain to 1.77.2
